# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
xcode_project: LEOTextView.xcworkspace
xcode_scheme: LEOTextView
xcode_sdk: iphonesimulator10.0