language: objective-c

branches:
  only:
  - develop
  - master

osx_image: xcode8

podfile: Example/Podfile

xcode_workspace: Example/NCKTextView.xcworkspace
xcode_scheme: NCKTextView-Example
xcode_sdk: iphonesimulator9.3
