language: objective-c

branches:
  only:
  - develop
  - master

osx_image: xcode7.3

podfile: Example/Podfile

xcode_project: Example/NCKTextView.xcodeproj
xcode_scheme: NCKTextView_Tests
xcode_sdk: iphonesimulator9.3
